# <method> <url> <version>
# <headers>
# <empty line>
# <body>

### query param
GET http://google.com?name=asd&version=1&anotherQueryParam=true
Accept: application/json, application/xml

### path param/path variable
GET http://google.com/{someId}

###
POST http://google.com/{someId}
Content-Type: application/json

{
  "firstName": "Paweł",
  "lastName": "Pustelnik",
  "address": {
    "buildingNumber": 13
  },
  "exampleArray": [
    "test",
    13,
    {
    }
  ]
}
